### ISSUE TITLE
Can't install Gadael

### ISSUE THREAD

**Issue by nOundO** [gadael/gadael#3]
Hello.
I cannot install the software. I've tried with Ubuntu 17.10, Ubuntu 16.04, Ubuntu 16.10, Debian, Fedora and CentOS.
None of the installation methods works.
The main problem is that nodejs-legacy package has dissappeared, now is integrated with nodejs. I've tried to force installation but initialization scripts don't work.

**Comment by polo2ro** [comment]
I will look into the problem, this will probably work if I rebuild the package with a nodejs dependency instead of nodejs-legacy. The main problem is to have a "node" binary instead of nodejs. maybe you will have to symlink the binary manually

**Comment by jbcebe-seekers** [comment]
@nOundO I got passed that error by using a base docker image preinstalled with npm.

```bash
docker run --name gadael -it -p 3000:3000 node:9.11.1 bash

# inside the container...
apt install mongodb git g++ gyp gcc make
npm install -g bower

adduser gadael
su - gadael
git clone https://github.com/gadael/gadael
cd gadael
npm install
bower install
```

however i get a different issue later on, bower stumples on one of the dependencies: `moment-duration-format` doesn't have a dev branch anymore it seems

**Comment by jbcebe-seekers** [comment]
follow-up: after editing bower.json to a valid version for `moment-duration-format` such as 2.2.2 then `bower install completes`

However the service fails to start...
```bash
$ node install.js gadael "ACME" EN
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '../config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)

```

**Comment by polo2ro** [comment]
you can copy the config.example.js in config.js and update the file with your settings, i thought "node install.js" should have done this for you, maybe this is an access right problem?

**Comment by monica7194** [comment]
Hello,
 I tried deploy in aws ,i got the error as cannot find the module.
And when i tried in heroku, the error is push rejected failed to compile node js app.

**Comment by monica7194** [comment]
Could you help me to resolve these errors.

**Comment by luixal** [comment]
Also hit the `Error: Cannot find module '../config'` error. As @polo2ro said, just copied `config.example.js` as `config.js` and it worked (dispite having to kill the script):

```
(node:28464) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:28464) DeprecationWarning: collection.remove is deprecated. Use deleteOne, deleteMany, or bulkWrite instead.
Database gadael created, please use `node app.js 3000 gadael` to start your Gadael instance

^C
```

After that, when i run `node app.js 3000` things won't work with this error message:

```
node:28873) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Error: createDb: Database already initialized with company object: gadael
    at gadael_loadMockModels.then.then.count (/home/nemesis/dev/oss/gadael/api/Company.api.js:268:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I've tried commenting the `config.mongodb.init: true` option in `config.js` with no luck, still getting the same message. I'ts due to the `saveCompanyDoc` function counting if company already exists.

Any idea on this?

**Comment by luixal** [comment]
Ok, just got it. After copying config.js and running the `node install.js [...]` command, you have to set `config.mongodb.init` specifically to **`false`**, isn't enough to comment it out.

Now it's working :)
